### ISSUE TITLE
GitHub Pages + GitHub Actions breaking config

### ISSUE THREAD

**Issue by krusynth** [publicinteresttown/pit-jekyll#4]
So I've _manually_ created the GitHub Actions file that builds the main branch and pushes the results to the `gh-pages` branch, and that seems to be conflicting with the GitHub Pages configuration. On each push, it's deleting the custom domain. I suspect that that file needs to be deleted, and then the contents manually added through the GitHub interface. Seems like a bug in GitHub but in the meantime every deploy deletes the custom domain. Needs a fix ASAP.

**Comment by BryceStevenWilley** [comment]
I think this can be fixed by putting the `CNAME` file in main as well. Jekyll should just copy all of the files from the main branch when deploying, and I think it's getting removed because `CNAME` isn't in main.

**Comment by krusynth** [comment]
Hmm, [the documentation says:](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)


> A CNAME file in your repository file does not automatically add or remove a custom domain. Instead, you must configure the custom domain through your repository settings or through the API. For more information, see "[Managing a custom domain for your GitHub Pages site](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)" and the [Pages API reference documentation](https://docs.github.com/en/rest/pages#update-information-about-a-github-pages-site).

**Comment by krusynth** [comment]
Ok, I _think_ that did the trick.  But worth keeping an eye on!
